# load_fake_data.py
"""Load synthetic CSV data into the database.
Assumes CSV files are located in `../data/` (generated by generate_fake_data.py).
"""

import os
import sys
import pandas as pd

# Ensure project root (backend2) is in PYTHONPATH so "app" can be imported when running this script directly
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if project_root not in sys.path:
    sys.path.append(project_root)

# Now import the application models and DB utilities
from app.database import SessionLocal, engine, Base
from app import models

def load_table(csv_path: str, model_cls):
    """Load data from a CSV file into the given SQLAlchemy model.
    Handles duplicate primary keys, slugs and SKUs gracefully.
    """
    df = pd.read_csv(csv_path)
    # Clean data: replace NaN with None and drop timestamp columns if present
    df = df.where(pd.notnull(df), None)
    df = df.drop(columns=["created_at", "updated_at"], errors="ignore")
    records = df.to_dict(orient="records")
    with SessionLocal() as session:
        for rec in records:
            # Remove explicit id to let the DB assign it
            rec.pop("id", None)
            if model_cls.__tablename__ == "products":
                # Skip duplicates based on slug or sku
                slug_exists = session.query(model_cls).filter_by(slug=rec.get("slug")).first()
                sku_exists = session.query(model_cls).filter_by(sku=rec.get("sku")).first()
                if slug_exists or sku_exists:
                    continue
            obj = model_cls(**rec)
            session.add(obj)
        session.commit()
        print(f"Loaded {len(records)} rows into {model_cls.__tablename__}")

def main():
    # Resolve the data directory correctly
    # Determine data directory: use DATA_ROOT env var if set, otherwise default to backend2/data
    base_dir = os.getenv('DATA_ROOT') or os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "data"))
    # Ensure tables exist
    Base.metadata.create_all(bind=engine)
    # Load both base and extra product CSVs
    load_table(os.path.join(base_dir, "products.csv"), models.Product)
    load_table(os.path.join(base_dir, "extra_products.csv"), models.Product)

if __name__ == "__main__":
    main()
